spring:
  datasource:
    url: jdbc:mysql://localhost:3307/demo?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        show_sql: true

  sql:
    init:
      mode: always

jwt:
  secret: ZnJvbV9kZWVwX2Zsb3dfYXBwbGljYXRpb25fYmFja2VuZF9zZWNyZXRfa2V5XzEyMzQ1Njc4OTAxMjM0NTY3ODkw

app:
  cors:
    allowed-origins: http://localhost:3000
  auth:
    cookie:
      secure: false
      same-site: Lax
  rate-limit:
    # local 개발 / E2E 시 rate-limit 으로 막히지 않도록 사실상 무제한 처리
    normal-rate-limit: 100000
    write-operation-cost: 1
    session-start-cost: 1
    read-operation-cost: 1
  r2:
    endpoint: https://e88d07b01b24fe0128c47001d7db0076.r2.cloudflarestorage.com
    access-key: ${R2_ACCESS_KEY}
    secret-key: ${R2_SECRET_KEY}
    bucket: deep-flow
    public-url: https://pub-1946749051ee4fb6b5cb17f28943fc88.r2.dev
