spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false

app:
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:https://deep-flow-fe.vercel.app}
  auth:
    cookie:
      secure: true
      same-site: None
  ai:
    enabled: ${AI_ENABLED:false}
